apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: angular-jyothi
  name: angular-jyothi
spec:
  ports:
  - name: 80-3000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: angular-jyothi
  type: LoadBalancer
status:
  loadBalancer: {}
