apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ezycontracts
  name: ezycontracts
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ezycontracts
  type: ClusterIP
status:
  loadBalancer: {}
